### ISSUE TITLE
Accessing camera can be created with 4 slots

### ISSUE THREAD

**Issue by AIshreeR** [gdsc-bit/openCV-Basics#2]
We can improve this code by resizing the window and displaying the video in 4 slots (and rotate the cameras if needed) 

![image](https://user-images.githubusercontent.com/75234700/194770098-01563aec-10d8-4fc1-9743-caacda8e382d.png)

**Comment by remotewith** [comment]
Hey 
Do you mean to display only one camera in 4 slots
but in each slot we will have a different angle by that camera?
or you are trying to say 4 slots for 4 different cameras?

**Comment by AIshreeR** [comment]
Hi, Sorry I didn't get any notifications in mail. And yeah, I meant creating 4 slots using a single camera and displaying a different angle by that in those slots.
